[package]
name = "hft-backtest"
version = "0.1.0"
edition = "2021"

[dependencies]
hftbacktest = "0.3.2"
tracing-subscriber = "0.3.18"

[dev-dependencies]
tracing-subscriber = { version = "0.3.18", features = [] }
clap = { version = "4.5.4", features = ["derive"] }
